name: CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            configure_preset: conan-release
          - os: macos-latest
            configure_preset: conan-release
          - os: windows-latest
            configure_preset: conan-release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install and configure Conan
        uses: conan-io/setup-conan@v1
        with:
          cache_packages: true

      - name: Set up Visual Studio shell
        if: matrix.os == 'windows-latest'
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Install dependencies via Conan
        run: |
          git clone https://github.com/hollykbuck/stdexec.git
          cd stdexec
          git checkout 086ccb28f85dcd7103247b6b56db540083e3a556
          conan export .
          cd ..
          conan install . --build=missing -s build_type=Release -s compiler.cppstd=20  -c="tools.cmake.cmaketoolchain:generator=Ninja" -c "tools.build:skip_test=True"

      - name: Configure CMake
        run: |
          cmake --preset ${{ matrix.configure_preset }}

      - name: Build
        run: |
          cmake --build --preset conan-release

      - name: Run tests
        run: ctest --preset ${{ matrix.configure_preset }} --output-on-failure
